// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationController from "./application_controller.js"
application.register("application", ApplicationController)

import ContactController from "./contact_controller.js"
application.register("contact", ContactController)

import CounterController from "./counter_controller.js"
application.register("counter", CounterController)

import SearchController from "./search_controller.js"
application.register("search", SearchController)
